#!/bin/bash

if [[ "$DEBUG" = "1" ]]; then
  set -x
  BASH_CMD_FLAGS='-x'
fi

## Functions

__loadSecrets() {
  # Load env vars
  printf "$(date) ENTRYPOINT: Loading docker secrets if exists...\n";
  for i in $(env|grep '/run/secrets')
  do
      varName=$(echo $i|awk -F '[=]' '{print $1}'|sed 's/_FILE//')
      varFile=$(echo $i|awk -F '[=]' '{print $2}')
      exportCmd="export $varName=$(cat $varFile)"
      printf "$(date)             Exporting var: $varName\n";
      eval "${exportCmd}"
  done
}

## Main

__loadSecrets

# Check if app-config is present
if [ -f /app-config ]; then
    # We expect that app-config handles the launch of app command
    printf "$(date) ENTRYPOINT: Executing app-config...\n";
    . /app-config "$@"
else
    # Let default CMD run if app-config is missing
    printf "$(date) ENTRYPOINT: Custom script app-config was not available\n";
    printf "$(date) ENTRYPOINT: Executing given parameters or default CMD\n";
    exec $@
fi
